services:
  shard_eu_1:
    container_name: shard_eu_1
    image: mongo:latest
    restart: unless-stopped
    command: mongod --shardsvr --replSet shard_eu_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20001:27017
    volumes:
      - shard_eu_data_1:/data/db
    networks:
      - mongo_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  shard_eu_2:
    container_name: shard_eu_2
    image: mongo:latest
    restart: unless-stopped
    command: mongod --shardsvr --replSet shard_eu_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20002:27017
    volumes:
      - shard_eu_data_2:/data/db
    networks:
      - mongo_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  shard_eu_3:
    container_name: shard_eu_3
    image: mongo:latest
    restart: unless-stopped
    command: mongod --shardsvr --replSet shard_eu_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20003:27017
    volumes:
      - shard_eu_data_3:/data/db
    networks:
      - mongo_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  shard_eu_data_1:
  shard_eu_data_2:
  shard_eu_data_3:

networks:
  mongo_network:
    external:
      name: mongo_network