/**
 * @fileoverview gRPC-Web generated client stub for lightbulb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: lightbulb.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.lightbulb = require('./lightbulb_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.lightbulb.LightbulbServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.lightbulb.LightbulbServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.lightbulb.GetStateRequest,
 *   !proto.lightbulb.LightbulbState>}
 */
const methodDescriptor_LightbulbService_GetState = new grpc.web.MethodDescriptor(
  '/lightbulb.LightbulbService/GetState',
  grpc.web.MethodType.UNARY,
  proto.lightbulb.GetStateRequest,
  proto.lightbulb.LightbulbState,
  /**
   * @param {!proto.lightbulb.GetStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.lightbulb.LightbulbState.deserializeBinary
);


/**
 * @param {!proto.lightbulb.GetStateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.lightbulb.LightbulbState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServiceClient.prototype.getState =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/lightbulb.LightbulbService/GetState',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_GetState,
      callback);
};


/**
 * @param {!proto.lightbulb.GetStateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.lightbulb.LightbulbState>}
 *     Promise that resolves to the response
 */
proto.lightbulb.LightbulbServicePromiseClient.prototype.getState =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/lightbulb.LightbulbService/GetState',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_GetState);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.lightbulb.SetPowerRequest,
 *   !proto.lightbulb.LightbulbState>}
 */
const methodDescriptor_LightbulbService_SetPower = new grpc.web.MethodDescriptor(
  '/lightbulb.LightbulbService/SetPower',
  grpc.web.MethodType.UNARY,
  proto.lightbulb.SetPowerRequest,
  proto.lightbulb.LightbulbState,
  /**
   * @param {!proto.lightbulb.SetPowerRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.lightbulb.LightbulbState.deserializeBinary
);


/**
 * @param {!proto.lightbulb.SetPowerRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.lightbulb.LightbulbState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServiceClient.prototype.setPower =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetPower',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetPower,
      callback);
};


/**
 * @param {!proto.lightbulb.SetPowerRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.lightbulb.LightbulbState>}
 *     Promise that resolves to the response
 */
proto.lightbulb.LightbulbServicePromiseClient.prototype.setPower =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetPower',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetPower);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.lightbulb.SetBrightnessRequest,
 *   !proto.lightbulb.LightbulbState>}
 */
const methodDescriptor_LightbulbService_SetBrightness = new grpc.web.MethodDescriptor(
  '/lightbulb.LightbulbService/SetBrightness',
  grpc.web.MethodType.UNARY,
  proto.lightbulb.SetBrightnessRequest,
  proto.lightbulb.LightbulbState,
  /**
   * @param {!proto.lightbulb.SetBrightnessRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.lightbulb.LightbulbState.deserializeBinary
);


/**
 * @param {!proto.lightbulb.SetBrightnessRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.lightbulb.LightbulbState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServiceClient.prototype.setBrightness =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetBrightness',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetBrightness,
      callback);
};


/**
 * @param {!proto.lightbulb.SetBrightnessRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.lightbulb.LightbulbState>}
 *     Promise that resolves to the response
 */
proto.lightbulb.LightbulbServicePromiseClient.prototype.setBrightness =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetBrightness',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetBrightness);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.lightbulb.SetColorTemperatureRequest,
 *   !proto.lightbulb.LightbulbState>}
 */
const methodDescriptor_LightbulbService_SetColorTemperature = new grpc.web.MethodDescriptor(
  '/lightbulb.LightbulbService/SetColorTemperature',
  grpc.web.MethodType.UNARY,
  proto.lightbulb.SetColorTemperatureRequest,
  proto.lightbulb.LightbulbState,
  /**
   * @param {!proto.lightbulb.SetColorTemperatureRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.lightbulb.LightbulbState.deserializeBinary
);


/**
 * @param {!proto.lightbulb.SetColorTemperatureRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.lightbulb.LightbulbState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServiceClient.prototype.setColorTemperature =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetColorTemperature',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetColorTemperature,
      callback);
};


/**
 * @param {!proto.lightbulb.SetColorTemperatureRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.lightbulb.LightbulbState>}
 *     Promise that resolves to the response
 */
proto.lightbulb.LightbulbServicePromiseClient.prototype.setColorTemperature =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/lightbulb.LightbulbService/SetColorTemperature',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_SetColorTemperature);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.lightbulb.StreamStateRequest,
 *   !proto.lightbulb.LightbulbState>}
 */
const methodDescriptor_LightbulbService_StreamState = new grpc.web.MethodDescriptor(
  '/lightbulb.LightbulbService/StreamState',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.lightbulb.StreamStateRequest,
  proto.lightbulb.LightbulbState,
  /**
   * @param {!proto.lightbulb.StreamStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.lightbulb.LightbulbState.deserializeBinary
);


/**
 * @param {!proto.lightbulb.StreamStateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServiceClient.prototype.streamState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/lightbulb.LightbulbService/StreamState',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_StreamState);
};


/**
 * @param {!proto.lightbulb.StreamStateRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.lightbulb.LightbulbState>}
 *     The XHR Node Readable Stream
 */
proto.lightbulb.LightbulbServicePromiseClient.prototype.streamState =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/lightbulb.LightbulbService/StreamState',
      request,
      metadata || {},
      methodDescriptor_LightbulbService_StreamState);
};


module.exports = proto.lightbulb;

