# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lightbulb.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lightbulb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flightbulb.proto\x12\tlightbulb\"\x11\n\x0fGetStateRequest\" \n\x0fSetPowerRequest\x12\r\n\x05is_on\x18\x01 \x01(\x08\"*\n\x14SetBrightnessRequest\x12\x12\n\nbrightness\x18\x01 \x01(\x05\"1\n\x1aSetColorTemperatureRequest\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\"\x14\n\x12StreamStateRequest\"N\n\x0eLightbulbState\x12\r\n\x05is_on\x18\x01 \x01(\x08\x12\x12\n\nbrightness\x18\x02 \x01(\x05\x12\x19\n\x11\x63olor_temperature\x18\x03 \x01(\x05\x32\x93\x03\n\x10LightbulbService\x12\x43\n\x08GetState\x12\x1a.lightbulb.GetStateRequest\x1a\x19.lightbulb.LightbulbState\"\x00\x12\x43\n\x08SetPower\x12\x1a.lightbulb.SetPowerRequest\x1a\x19.lightbulb.LightbulbState\"\x00\x12M\n\rSetBrightness\x12\x1f.lightbulb.SetBrightnessRequest\x1a\x19.lightbulb.LightbulbState\"\x00\x12Y\n\x13SetColorTemperature\x12%.lightbulb.SetColorTemperatureRequest\x1a\x19.lightbulb.LightbulbState\"\x00\x12K\n\x0bStreamState\x12\x1d.lightbulb.StreamStateRequest\x1a\x19.lightbulb.LightbulbState\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lightbulb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATEREQUEST']._serialized_start=30
  _globals['_GETSTATEREQUEST']._serialized_end=47
  _globals['_SETPOWERREQUEST']._serialized_start=49
  _globals['_SETPOWERREQUEST']._serialized_end=81
  _globals['_SETBRIGHTNESSREQUEST']._serialized_start=83
  _globals['_SETBRIGHTNESSREQUEST']._serialized_end=125
  _globals['_SETCOLORTEMPERATUREREQUEST']._serialized_start=127
  _globals['_SETCOLORTEMPERATUREREQUEST']._serialized_end=176
  _globals['_STREAMSTATEREQUEST']._serialized_start=178
  _globals['_STREAMSTATEREQUEST']._serialized_end=198
  _globals['_LIGHTBULBSTATE']._serialized_start=200
  _globals['_LIGHTBULBSTATE']._serialized_end=278
  _globals['_LIGHTBULBSERVICE']._serialized_start=281
  _globals['_LIGHTBULBSERVICE']._serialized_end=684
# @@protoc_insertion_point(module_scope)
